package View;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import proyectolenguajes.ConexionBD;

public class ListarproductoView extends javax.swing.JFrame {

    public ListarproductoView() {
        initComponents();
        Mostrar_datos.setText("Mostrar datos");
        Mostrar_datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mostrar_datosActionPerformed(evt);
            }
        });

        Limpiar_datos.setText("Limpiar datos");
        Limpiar_datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarDatosActionPerformed(evt);
            }
        });
    }

    private void LimpiarDatosActionPerformed(java.awt.event.ActionEvent evt) {
        // Obtener el modelo de la tabla
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) MostrarProducto.getModel();
        model.setRowCount(0); // Limpiar todas las filas
    }

    private void Mostrar_datosActionPerformed(java.awt.event.ActionEvent evt) {
        // Obtener el modelo de la tabla
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) MostrarProducto.getModel();
        model.setRowCount(0); // Limpiar el modelo de la tabla antes de agregar nuevos datos

        // Configurar conexión y consulta
        ConexionBD conexionBD = new ConexionBD();
        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;
        try {
            conn = conexionBD.conectar();
            if (conn != null) {
                System.out.println("Conexión establecida correctamente.");
                String query = "SELECT ID_PRODUCTO, ID_CATEGORIA, ID_PROVEEDOR, NOMBRE_PRODUCTO, INVENTARIO, PRECIO_VENTA, PRECIO_COMPRA FROM PROYECTOADMIN.PRODUCTOS";
                stmt = conn.createStatement();
                rs = stmt.executeQuery(query);

                // Verificar si el ResultSet tiene datos y llenar la tabla
                boolean hasData = false;
                while (rs.next()) {
                    hasData = true;
                    int idProducto = rs.getInt("ID_PRODUCTO");
                    int idCategoria = rs.getInt("ID_CATEGORIA");
                    int idProveedor = rs.getInt("ID_PROVEEDOR");
                    String nombreProducto = rs.getString("NOMBRE_PRODUCTO");
                    int inventario = rs.getInt("INVENTARIO");
                    double precioVenta = rs.getDouble("PRECIO_VENTA");
                    double precioCompra = rs.getDouble("PRECIO_COMPRA");

                    model.addRow(new Object[]{idProducto, idCategoria, idProveedor, nombreProducto, inventario, precioVenta, precioCompra});
                }

                if (!hasData) {
                    System.out.println("El ResultSet está vacío.");
                } else {
                    System.out.println("Número de filas en el modelo: " + model.getRowCount());
                }
            } else {
                System.out.println("Conexión fallida.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error de SQL: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } finally {
            // Cerrar ResultSet, Statement y Connection
            if (rs != null) {
                try {
                    rs.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
            if (stmt != null) {
                try {
                    stmt.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
            conexionBD.cerrarConexion(conn);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        regreso2 = new javax.swing.JButton();
        Mostrar_datos = new javax.swing.JButton();
        Limpiar_datos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        MostrarProducto = new javax.swing.JTable();
        jLabelBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(67, 67, 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Goudy Stout", 0, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(153, 104, 34));
        Titulo.setText("UNDER FIRE");
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 581, 47));

        regreso2.setText("Regresar");
        regreso2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regreso2MouseClicked(evt);
            }
        });
        regreso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regreso2ActionPerformed(evt);
            }
        });
        jPanel1.add(regreso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1006, 439, 129, 51));

        Mostrar_datos.setText("Mostrar datos");
        jPanel1.add(Mostrar_datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 439, 144, 51));

        Limpiar_datos.setText("Limpiar datos");
        jPanel1.add(Limpiar_datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(722, 439, 162, 51));

        MostrarProducto.setBackground(new java.awt.Color(255, 255, 255));
        MostrarProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "IdProducto", "IdCategoria", "IdProveedor", "NombreProducto", "CantidadInventario", "PrecioVenta", "Title 7"
            }
        ));
        jScrollPane2.setViewportView(MostrarProducto);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 58, 1108, 375));

        jLabelBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.png"))); // NOI18N
        jPanel1.add(jLabelBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 1180, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regreso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regreso2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regreso2ActionPerformed

    private void regreso2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regreso2MouseClicked
        dispose();
    }//GEN-LAST:event_regreso2MouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarproductoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarproductoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarproductoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarproductoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarproductoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Limpiar_datos;
    private javax.swing.JTable MostrarProducto;
    private javax.swing.JButton Mostrar_datos;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel jLabelBG;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton regreso2;
    // End of variables declaration//GEN-END:variables
}
